//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Construction_Tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assembly
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assembly()
        {
            this.project_assemblies = new HashSet<project_assemblies>();
        }
    
        public int ASSEMBLY_ID { get; set; }
        public int CAT_ID { get; set; }
        public int SUB_CAT_ID { get; set; }
    
        public virtual assemblies_category assemblies_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_assemblies> project_assemblies { get; set; }
        public virtual assemblies_subcategory assemblies_subcategory { get; set; }
    }
}
