//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Construction_Tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        public int PROJECT_ID { get; set; }
        public string ITEM_ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual item item { get; set; }
        public virtual project project { get; set; }
    }
}
