//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Construction_Tool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModels : DbContext
    {
        public DBModels()
            : base("name=DBModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assembly> assemblies { get; set; }
        public virtual DbSet<assemblies_category> assemblies_category { get; set; }
        public virtual DbSet<assemblies_subcategory> assemblies_subcategory { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<material> materials { get; set; }
        public virtual DbSet<owner> owners { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<project_assemblies> project_assemblies { get; set; }
    }
}
